# Generated by Django 4.2.4 on 2023-08-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default='efef', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
